version: '3'
services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nakama:
    image: heroiclabs/nakama:3.12.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database Configuration
      - DATABASE_ADDRESS=postgres:localdb@postgres:5432/nakama
      
      # Cognito Configuration - UPDATE THESE VALUES
      - NAKAMA_COGNITO_ISS=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_CHANGEME
      - NAKAMA_COGNITO_AUDIENCE=your-app-client-id-CHANGEME
      
      # JWKS Cache Configuration (optional)
      - NAKAMA_JWKS_CACHE_TTL=3600
      
      # Wallet Configuration (optional)
      - NAKAMA_WALLET_ENABLED=false
      # - NAKAMA_WALLET_CHAIN=evm
      # - NAKAMA_WALLET_MASTER_KEY_ARN=arn:aws:kms:us-east-1:123456789012:key/CHANGEME
      # - NAKAMA_WALLET_DERIVATION_PATH=m/44'/60'/0'/0
      
      # Nakama Configuration
      - LOG_LEVEL=DEBUG
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        /nakama/nakama 
        --database.address postgres:localdb@postgres:5432/nakama
        --runtime.path /nakama/data/modules
        --logger.level DEBUG
        --console.username admin
        --console.password password
    ports:
      - "7349:7349"  # gRPC
      - "7350:7350"  # HTTP API
      - "7351:7351"  # Console
    volumes:
      - ./modules:/nakama/data/modules
    restart: unless-stopped

volumes:
  data:
