#!/usr/bin/env bash
# Fail if a credential literal is committed into the Nakama runtime modules.
#
# Why this exists
# ---------------
# A bcrypt admin-password hash and a set of Satori / Appodeal / news-API keys
# were committed into data/modules/** and shipped inside the production image.
# master has since been cleaned of the bcrypt hash, but roughly 110 stale
# branches still carry it, so a late merge can silently reintroduce a
# known-exposed hash into the image. .gitattributes already records the lesson
# that "a guard that runs in CI is the one that actually gates the deploy".
#
# This is a ratchet, not a big bang:
#
#   Rule 1 (bcrypt hash)        BLOCKING - master is clean today, keep it that way.
#   Rule 2 (credential literal) BLOCKING for new files; the already-known
#                               offenders are listed in KNOWN_OUTSTANDING and
#                               reported as warnings until each is converted to
#                               an environment read. Shrink that list; never
#                               grow it.
#
# Both rules match on shape, not on specific values, so they keep working after
# the credentials are rotated.
set -uo pipefail

SCOPE=${1:-data/modules}

# Files that already contain credential literals and have a known owner /
# remediation. Remove entries as they are fixed. Do not add to this list.
KNOWN_OUTSTANDING=(
  # Satori API key + signing key -> converted to env reads in the
  # security/satori-creds-from-env PR; drop these two once that lands.
  "data/modules/satori_direct/satori_direct.js"
  # Appodeal API key / user id / app key - still literals.
  "data/modules/external_analytics/external_analytics.js"
  # TMDB, GNews, NewsAPI, Currents, Mediastack, NASA, RestCountries.
  "data/modules/src/games/quizverse/question_cache.ts"
  # Generated bundles: these mirror whatever the sources above contain and are
  # regenerated by postbuild.js, so they clear themselves once the sources do.
  "data/modules/index.js"
  "data/modules/build/index.js"
)

is_known() {
  local f=$1 k
  for k in "${KNOWN_OUTSTANDING[@]}"; do
    [ "$f" = "$k" ] && return 0
  done
  return 1
}

fail=0
warn=0

# ── Rule 1: bcrypt hashes ($2a/$2b/$2y + cost + 53-char tail). ─────────────
# A doc example that stops at "$2y$12$..." does not match.
while IFS=: read -r f n _; do
  [ -z "${f:-}" ] && continue
  printf '::error file=%s,line=%s::bcrypt hash literal committed in %s\n' "$f" "$n" "$SCOPE"
  fail=1
done < <(grep -rInE '\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}' "$SCOPE" 2>/dev/null)

# ── Rule 2: long literal assigned to a credential-shaped name. ─────────────
while IFS=: read -r f n _; do
  [ -z "${f:-}" ] && continue
  if is_known "$f"; then
    printf '::warning file=%s,line=%s::credential literal in a known-outstanding file (see KNOWN_OUTSTANDING)\n' "$f" "$n"
    warn=$((warn + 1))
  else
    printf '::error file=%s,line=%s::credential-shaped literal assigned to a *_KEY/_SECRET/_TOKEN/_PASSWORD name\n' "$f" "$n"
    fail=1
  fi
done < <(grep -rInE '(API_KEY|SIGNING_KEY|SECRET_KEY|_SECRET|_TOKEN|_PASSWORD|PRIVATE_KEY)[A-Z_]*"?[[:space:]]*[:=][[:space:]]*"[A-Za-z0-9+/=_-]{32,}"' "$SCOPE" 2>/dev/null)

if [ "$fail" -ne 0 ]; then
  cat >&2 <<'MSG'

A credential literal is present in the runtime modules.

Read it from the environment instead, with NO literal fallback:

    var v = (ctx && ctx.env && ctx.env.MY_KEY) ? String(ctx.env.MY_KEY).trim() : "";

and add the key name to runtime.env in nakama-secret - Nakama's JS runtime
only sees keys listed there. A literal fallback defeats rotation, which is
how this happened the first time.

If you are merging an older branch, the offending line is probably a stale
credential that master has already removed: take master's version.
MSG
  exit 1
fi

echo "OK: no new credential literals in $SCOPE ($warn known-outstanding warning(s))"
